AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM Template for AWS
Resources:
  s3BucketInCloudInput:
    Type: AWS::S3::Bucket
    DependsOn: s3SNSsqsTopic
    Properties:
      BucketName: rcyganczuk-in-cloud-bucket-input
      NotificationConfiguration:
        TopicConfigurations:
        - Topic:
            Ref: s3SNSsqsTopic
          Event: s3:ObjectCreated:*
  s3SNSsqsTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Fn::GetAtt:
          - snsSQSlambdaQueue
          - Arn
        Protocol: sqs
      TopicName: s3SNSsqsTopic
  s3SNSsqsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    DependsOn: s3SNSsqsTopic
    Properties:
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: s3.amazonaws.com
          Action:
          - sns:Publish
          Resource:
            Ref: s3SNSsqsTopic
          Condition:
            ArnEquals:
              aws:SourceArn: arn:aws:s3:::rcyganczuk-in-cloud-bucket-input
      Topics:
      - Ref: s3SNSsqsTopic
  snsSQSlambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      QueueName: snsSQSlambdaQueue
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
  snsSQSlambdaQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: snsSQSlambdaQueue
    Properties:
      PolicyDocument:
        Statement:
        - Sid: Allow-SNS-SendMessage
          Effect: Allow
          Principal:
            Service: sns.amazonaws.com
          Action:
          - sqs:SendMessage
          Resource:
            Fn::GetAtt:
            - snsSQSlambdaQueue
            - Arn
          Condition:
            ArnEquals:
              aws:SourceArn:
                Ref: s3SNSsqsTopic
      Queues:
      - Ref: snsSQSlambdaQueue
  lambdaSQSlambdaQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      QueueName: lambdaSQSlambdaQueue
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
  deadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      MessageRetentionPeriod: 345600
      QueueName: deadLetterQueue
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 30
  sqsLAMBDAsqs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sqsLAMBDAsqs
      Handler: helloworld.Handler::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: arn:aws:iam::910682323108:role/aws-jdk-tool-HelloWorldFunctionRole-FQMTW660F1QY
      Events:
        ReadWriteSQSLambdaSQS:
          Type: SQS
          Properties:
            Queue:
              Fn::GetAtt:
              - snsSQSlambdaQueue
              - Arn
            BatchSize: 10
            Enabled: true
      CodeUri: s3://rcyganczuk-in-cloud-bucket-output/a9732de2f6952bef75e99e5ff0d040d6
